name: Build
on: [push, pull_request]
jobs:
  build:
    name: node v${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 19]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: '**/package.json'
      - run: npm install
      - name: Run Tests
        run: ./node_modules/.bin/dak workspace-p.dak cover
