name: Build
on: [push, pull_request]
jobs:
  build:
    name: bun / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: ./src/transpiler.dak
      - run: git status --porcelain
      - run: bun test $(ls ./test/*.dak)

  deploy:
    name: website
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: ./src/website.dak
      - name: install rclone
        run: |
          cd /tmp
          wget --quiet https://downloads.rclone.org/rclone-current-linux-amd64.deb
          sudo dpkg -i rclone-current-linux-amd64.deb
      - name: deploy
        run: rclone --config .rclone.conf copyto dist/ s3:www.daklang.com/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
