name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Type of version bump'
        required: true
        default: 'minor'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
      - name: Publish
        run: |
          git config --global user.name 'Naitik Shah'
          git config --global user.email 'daaku@users.noreply.github.com'
          ./node_modules/.bin/dak make.dak release ${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
